### ISSUE TITLE
Docker init script does not create any type

### ISSUE THREAD

**Issue by Methrat0n** [edgedb/edgedb-docker#29]
While starting a new project I decide to use this database as I quiet like the idea and the features you added on top of postgreSQL. I try using your provided docker as I prefer my team to be able to start our whole stack by a simple `docker-compose up` but I cant get it to work.

Here is the relevant part of the docker-compose :
```
  gateway-db:
    build:
      dockerfile: dockers/gatewayDB-Dockerfile
      context: .
    restart: unless-stopped
    container_name: gateway-db
    ports:
      - "5656:5656"
    environment:
      EDGEDB_AUTH_METHOD: "trust"
      EDGEDB_GENERATE_SELF_SIGNED_CERT: 1
```

The dockerfile : 
```
FROM edgedb/edgedb

COPY ./dockers/gatewayDB-default.esdl /edgedb-bootstrap.d/default.esdl
```

And finally the esdl :
```
module default {
  type Subscription {
    required property libraryUrl -> str;
  }
};

using extension graphql;
using extension edgeql_http;
```

The container do start and everything seams ok but I cant get a request to work.
I use the official edgeDb cli to connect to my container and can execute requests. For example I can list all tables : 
```
edgedb> SELECT name := schema::ObjectType.name;
{
  'std::BaseObject',
  'std::Object',
  'std::FreeObject',
  'schema::Object',
  'schema::SubclassableObject',
  'schema::Type',
  'schema::PseudoType',
  'schema::Module',
  'schema::CollectionType',
  'schema::Array',
  'schema::TupleElement',
  'schema::Tuple',
  'schema::Delta',
  'schema::Annotation',
  'schema::AnnotationSubject',
  'schema::InheritingObject',
  'schema::Parameter',
  'schema::CallableObject',
  'schema::VolatilitySubject',
  'schema::Constraint',
  'schema::ConsistencySubject',
  'schema::Index',
  'schema::Source',
  'schema::Pointer',
  'schema::Alias',
  'schema::ScalarType',
  'schema::ObjectType',
  'schema::Link',
  'schema::Property',
  'schema::Function',
  'schema::Operator',
  'schema::Cast',
  'schema::Migration',
  'schema::Extension',
  'sys::SystemObject',
  'sys::Database',
  'sys::ExtensionPackage',
  'sys::Role',
  'cfg::ConfigObject',
  'cfg::AuthMethod',
  'cfg::Trust',
  'cfg::SCRAM',
  'cfg::Auth',
  'cfg::AbstractConfig',
  'cfg::Config',
  'cfg::InstanceConfig',
  'cfg::DatabaseConfig',
}
```

But, as you see, the Subscription type does not seams to have been created and I cant do any request on it : 
```
edgedb> SELECT Subscription;
error: object type or alias 'default::Subscription' does not exist
  ┌─ query:1:8
  │
1 │ SELECT Subscription;
  │        ^^^^^^^^^^^^ error
```

Therefore I think there is a problem in your docker or maybe further inside, I dunno :(
