### ISSUE TITLE
Can't remotely connect to docker container

### ISSUE THREAD

**Issue by briand617** [edgedb/edgedb-docker#56]
With my `docker-compose.yml` set to this on Ubuntu-18: 
```
  edgedb:
    container_name: test_edgedb
    image: edgedb/edgedb
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    volumes:
      - "./dbschema:/dbschema"
      - "./edgedb.toml:/edgedb.toml"
      - "./credentials:/root/.config/edgedb/credentials"
    ports:
      - "5656"    
 ```
I am able to go into the edgedb shell and create a database and make queries. My username is set to `edgedb` and my database is named `default`

However, when I'm outside the edgedb shell, I can't make the remote connection....

```
$ edgedb --dsn=edgedb://edgedb@localhost:5656/default
Connecting to an EdgeDB instance at localhost:5656...
edgedb error: ClientConnectionFailedError: cannot establish connection for 30s: Connection refused (os error 111)
```

Likewise, from another docker container running a Typescript image, I get corresponding errors when I use this connection:

```
    const client = edgedb.createClient({
      dsn: 'edgedb://edgedb@edgedb:5656/default'
    });
```

Is there a working example of remote EdgeDB connections within the context of a Docker container environment?
